
name: PyInstaller Windows

on:
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@v0.1.2


      with:
        path: .

    - uses: actions/upload-artifact@v2
      with:
        name: AutomaticBackupForSunkenland.exe
        path: src/dist/windows
